name: 'SDC Session'
type: 'Site'
recipes:
  - core/recipes/standard
install:
  - default_content
  - sdc_session
config:
  actions:
    system.theme:
      simple_config_update:
        default: 'sdc_session'
